Repository wazo-platform/wazo-agentd, pull requests merged in 2021-07, with the labels that each got.

#49 set pg application_name
  etc/wazo-agentd/config.yml
Labels: mergeit

#50 Add a Jenkinsfile
  Jenkinsfile
Labels: auto-merge

#51 fix openapi: agent number is a string not integer
  wazo_agentd/swagger/api.yml
Labels: auto-merge, mergeit
